export const trigonometryPath = {
        name: 'Trigonometry Path',
        icon: '📊',
        lessons: [

            // ---- 1. Intro to Trigonometry ----
            { id: 'intro-trig', title: 'Introduction to Trigonometry', subtitle: 'Angles and right triangles', xpReward: 30, sections: [
                { type: 'text', content: `<h3>What Is Trigonometry?</h3><p>Trigonometry is the study of the relationship between <strong>angles</strong> and <strong>side lengths</strong> in triangles. It might sound abstract, but it's behind nearly everything: architects use it to design buildings, engineers use it to build bridges, and GPS satellites use it to pinpoint your location.</p><p>We focus on <strong>right triangles</strong> — triangles that have one 90° angle (a perfect corner). The angle we're interested in is usually labeled <strong>θ</strong> (the Greek letter "theta"). Depending on where θ is, each side of the triangle gets a name:</p><p>• <strong>Hypotenuse</strong> — the longest side, always opposite the 90° angle. It never changes regardless of which angle you pick.<br>• <strong>Opposite</strong> — the side directly across from θ (it doesn't touch θ).<br>• <strong>Adjacent</strong> — the side right next to θ (not the hypotenuse).</p><p>⚠️ Important: "opposite" and "adjacent" <em>depend on which angle you're looking at</em>. The same side can be "opposite" for one angle and "adjacent" for another.</p><h3>The Three Trig Ratios</h3><p>With these three sides, we create three ratios — the core of all trigonometry. The memory trick <strong>SOH-CAH-TOA</strong> tells you which sides go with which ratio:</p><p><strong>SOH → sin θ = Opposite / Hypotenuse</strong><br><strong>CAH → cos θ = Adjacent / Hypotenuse</strong><br><strong>TOA → tan θ = Opposite / Adjacent</strong></p>` },
                { type: 'example', title: 'Identifying Sides', content: `<p>Imagine a right triangle with angle θ at the bottom-left. The right angle is at the bottom-right.</p><p>• The side along the bottom (touching θ) → <strong>adjacent</strong><br>• The side going up on the right (across from θ) → <strong>opposite</strong><br>• The diagonal side from bottom-left to top-right (across from the 90° angle) → <strong>hypotenuse</strong></p><p>If θ were at the top of the triangle instead, the opposite and adjacent sides would swap roles!</p>` },
                { type: 'generated_practice', generators: ['sohcahtoa-which-func'] },
                { type: 'tips', content: `<h4>💡 Key Takeaways</h4><p><strong>SOH-CAH-TOA</strong> is your best friend in trig. Say it out loud a few times until it sticks.</p><p>The <strong>hypotenuse</strong> is always the longest side and always sits opposite the 90° corner — it never changes. "Opposite" and "adjacent" do change depending on which angle θ is.</p><p>A helpful way to remember: the hypotenuse is the one side that <em>doesn't touch</em> the right angle.</p>` },
                { type: 'practice', problems: [
                    { question: 'sin θ equals:', choices: ['adjacent/hypotenuse', 'opposite/hypotenuse', 'opposite/adjacent', 'hypotenuse/opposite'], correctIndex: 1, explanation: 'SOH: sin = <strong>opposite / hypotenuse</strong>.' },
                    { question: 'cos θ equals:', choices: ['opposite/hypotenuse', 'adjacent/hypotenuse', 'opposite/adjacent', 'hypotenuse/adjacent'], correctIndex: 1, explanation: 'CAH: cos = <strong>adjacent / hypotenuse</strong>.' },
                    { question: 'tan θ equals:', choices: ['adjacent/opposite', 'opposite/hypotenuse', 'opposite/adjacent', 'adjacent/hypotenuse'], correctIndex: 2, explanation: 'TOA: tan = <strong>opposite / adjacent</strong>.' },
                    { question: 'Which trig ratio uses the opposite side and hypotenuse?', choices: ['cos', 'tan', 'sin', 'adjacent/hypotenuse'], correctIndex: 2, explanation: '<strong>sin θ</strong> = opposite / hypotenuse.' },
                ]}
            ]},

            // ---- 2. Trig Ratios & Evaluation ----
            { id: 'trig-ratios', title: 'Evaluating Trig Ratios', subtitle: 'Finding sin, cos, tan from triangles', xpReward: 40, sections: [
                { type: 'text', content: `<h3>Computing Trig Ratios</h3><p>Given a right triangle with known side lengths, you can compute the exact trig ratios for any angle using SOH-CAH-TOA. The process is straightforward: identify the angle, label the sides relative to it (opposite, adjacent, hypotenuse), then plug into the correct ratio.</p><h3>What if a Side is Missing?</h3><p>Often you're given only two sides and need to find the third before you can compute all three ratios. That's where the <strong>Pythagorean theorem</strong> comes in:</p><p style="text-align:center;"><strong>a² + b² = c²</strong></p><p>where <strong>c</strong> is always the hypotenuse. So if you know two sides, you can solve for the third:</p><p>• Missing hypotenuse: c = √(a² + b²)<br>• Missing leg: a = √(c² − b²)</p><p>Example: if opposite = 5 and hypotenuse = 13, then adjacent = √(13² − 5²) = √(169 − 25) = √144 = <strong>12</strong>. Now you have all three sides and can find any ratio.</p>` },
                { type: 'example', title: 'Full Example: The 3-4-5 Triangle', content: `<p>A right triangle has sides 3, 4, and 5. Angle θ is opposite the side of length 3.</p><p>Label the sides relative to θ: opposite = 3, adjacent = 4, hypotenuse = 5.</p><p>sin θ = 3/5 &nbsp;|&nbsp; cos θ = 4/5 &nbsp;|&nbsp; tan θ = 3/4</p><p>Check: 3² + 4² = 9 + 16 = 25 = 5² ✓ It's a valid right triangle.</p>` },
                { type: 'generated_practice', generators: ['trig-ratio-from-sides'] },
                { type: 'tips', content: `<h4>💡 Key Takeaways</h4><p>Always identify <em>which angle</em> you're working with first — the labels opposite and adjacent flip depending on your angle.</p><p>If a side is missing, use the Pythagorean theorem (a² + b² = c²) to find it before applying SOH-CAH-TOA.</p><p>Pythagorean triples like 3-4-5, 5-12-13, and 8-15-17 are right triangles with whole-number sides — worth memorizing to save time!</p>` },
                { type: 'practice', problems: [
                    { question: 'Right triangle: opposite = 5, hypotenuse = 13. sin θ =', choices: ['5/13', '12/13', '5/12', '13/5'], correctIndex: 0, explanation: 'sin = opposite/hypotenuse = <strong>5/13</strong>.' },
                    { question: 'Right triangle: adjacent = 8, hypotenuse = 17. cos θ =', choices: ['15/17', '8/17', '8/15', '17/8'], correctIndex: 1, explanation: 'cos = adjacent/hypotenuse = <strong>8/17</strong>.' },
                    { question: 'Right triangle: opposite = 7, adjacent = 24. tan θ =', choices: ['7/25', '24/7', '7/24', '24/25'], correctIndex: 2, explanation: 'tan = opposite/adjacent = <strong>7/24</strong>.' },
                    { question: 'If sin θ = 3/5, what is cos θ? (3-4-5 triangle)', choices: ['3/5', '4/5', '5/4', '3/4'], correctIndex: 1, explanation: 'Use Pythagorean theorem: adjacent = √(5²−3²) = √16 = 4. cos θ = adjacent/hypotenuse = <strong>4/5</strong>.' },
                ]}
            ]},

            // ---- 3. Finding Sides with Trig ----
            { id: 'trig-find-sides', title: 'Finding Sides with Trig', subtitle: 'Using trig to solve for unknown sides', xpReward: 45, sections: [
                { type: 'text', content: `<h3>Solving for an Unknown Side</h3><p>If you know one side length and one acute angle, you can use trig ratios to find any other side. Think of it as treating the trig ratio as an equation and solving for the missing piece.</p><p>Here's the strategy:</p><p><strong>Step 1 — Label the sides</strong> relative to the known angle: which is opposite, adjacent, hypotenuse?</p><p><strong>Step 2 — Pick the right ratio</strong> — the one that connects the side you <em>know</em> and the side you <em>want</em>. SOH-CAH-TOA tells you which ratio uses which pair of sides.</p><p><strong>Step 3 — Set up the equation and solve.</strong> The ratio gives you a fraction; cross-multiply or rearrange to isolate the unknown.</p><p>Two common setups:</p><p>• <strong>If the unknown is on top</strong> (e.g., sin θ = x/hyp): multiply both sides by the hypotenuse → x = hyp × sin θ.<br>• <strong>If the unknown is on the bottom</strong> (e.g., sin θ = opp/x): multiply both sides by x, then divide by sin θ → x = opp/sin θ.</p>` },
                { type: 'example', title: 'Finding an Opposite Side', content: `<p><strong>Angle = 35°, hypotenuse = 10. Find the opposite side.</strong></p><p>I know the hypotenuse and want the opposite → use <strong>sin</strong> (SOH).</p><p>sin 35° = opposite / 10</p><p>Multiply both sides by 10: opposite = 10 × sin 35° ≈ 10 × 0.574 ≈ <strong>5.74</strong></p>` },
                { type: 'interactive_steps', title: 'Guided: Find the opposite side. Angle = 40°, adjacent = 12.', description: 'Choose the right ratio and solve.', steps: [
                    { text: 'We know adjacent and want opposite. Use {blank}', answer: 'tan', hint: 'TOA: tan = opposite/adjacent' },
                    { text: 'tan(40°) = opposite / {blank}', answer: '12', hint: 'The adjacent side is 12' },
                    { text: 'opposite = 12 × tan(40°) = 12 × {blank}', answer: '0.839', hint: 'tan(40°) ≈ 0.839' },
                    { text: 'opposite ≈ {blank}', answer: '10.1', hint: '12 × 0.839 ≈ ?' }
                ], result: 'The opposite side ≈ 10.1' },
                { type: 'practice', problems: [
                    { question: 'Angle 40°, adjacent = 12. Find opposite (use tan).', choices: ['12 tan 40°', '12 sin 40°', '12 cos 40°', '12/tan 40°'], correctIndex: 0, explanation: 'tan 40° = opp/12, so opp = <strong>12 tan 40°</strong>.' },
                    { question: 'Angle 50°, hypotenuse = 20. Find adjacent (use cos).', choices: ['20 sin 50°', '20 tan 50°', '20 cos 50°', '20/cos 50°'], correctIndex: 2, explanation: 'cos 50° = adj/20, so adj = <strong>20 cos 50°</strong>.' },
                    { question: 'Angle 60°, opposite = 9. Find hypotenuse (use sin).', choices: ['9 sin 60°', '9/sin 60°', '9 cos 60°', '9/cos 60°'], correctIndex: 1, explanation: 'sin 60° = 9/hyp, so hyp = <strong>9/sin 60°</strong>.' },
                    { question: 'Which ratio connects opposite and adjacent?', choices: ['sin', 'cos', 'tan', 'opposite/hypotenuse'], correctIndex: 2, explanation: '<strong>tan θ</strong> = opposite / adjacent.' },
                ]}
            ]},

            // ---- 4. Inverse Trig Functions ----
            { id: 'inverse-trig', title: 'Inverse Trig Functions', subtitle: 'Finding angles from ratios', xpReward: 45, sections: [
                { type: 'text', content: `<h3>Going Backwards: Ratios → Angles</h3><p>So far we've been going forwards: given an angle, find a ratio. But what if you know the ratio and want the angle? That's what <strong>inverse trig functions</strong> do — they run the process in reverse.</p><p>Think of it like division undoing multiplication: sin undoes… sin⁻¹, cos⁻¹ undoes cos, and tan⁻¹ undoes tan.</p><p>The notation looks like: <strong>θ = sin⁻¹(ratio)</strong>, also written as <strong>arcsin(ratio)</strong>. (The ⁻¹ here means "inverse function," not "1/sin"!)</p><h3>Key Angle Values to Know</h3><p>These values come up constantly — they're worth memorizing:</p><p>• sin 30° = <strong>1/2</strong> &nbsp;→&nbsp; sin⁻¹(1/2) = 30°<br>• sin 45° = <strong>√2/2</strong> &nbsp;→&nbsp; sin⁻¹(√2/2) = 45°<br>• sin 60° = <strong>√3/2</strong> &nbsp;→&nbsp; sin⁻¹(√3/2) = 60°</p><p>• cos 30° = <strong>√3/2</strong> &nbsp;→&nbsp; cos⁻¹(√3/2) = 30°<br>• cos 45° = <strong>√2/2</strong> &nbsp;→&nbsp; cos⁻¹(√2/2) = 45°<br>• cos 60° = <strong>1/2</strong> &nbsp;→&nbsp; cos⁻¹(1/2) = 60°</p><p>• tan 30° = <strong>1/√3</strong>, tan 45° = <strong>1</strong>, tan 60° = <strong>√3</strong></p><h3>Range of Inverse Trig Functions</h3><p>Since many angles share the same sin/cos/tan value, inverse trig functions are designed to return a single "principal" angle within a specific range:</p><p>• sin⁻¹ outputs angles in <strong>[−90°, 90°]</strong> (from straight down to straight up).<br>• cos⁻¹ outputs angles in <strong>[0°, 180°]</strong> (the upper half).<br>• tan⁻¹ outputs angles in <strong>(−90°, 90°)</strong>.</p>` },
                { type: 'example', title: 'Finding an Angle', content: `<p><strong>sin θ = 0.5</strong> → Ask: "what angle has a sine of 0.5?" → θ = sin⁻¹(0.5) = <strong>30°</strong>.</p><p><strong>tan θ = 1</strong> → Ask: "what angle has a tangent of 1?" → θ = tan⁻¹(1) = <strong>45°</strong>.</p><p>On a calculator, look for the sin⁻¹, cos⁻¹, tan⁻¹ buttons (usually accessed via SHIFT or 2nd).</p>` },
                { type: 'generated_practice', generators: ['inverse-trig-eval', 'inverse-trig-range'] },
                { type: 'practice', problems: [
                    { question: 'cos θ = √3/2. θ =', choices: ['30°', '45°', '60°', '90°'], correctIndex: 0, explanation: 'cos⁻¹(√3/2) = <strong>30°</strong>.' },
                    { question: 'sin θ = √2/2. θ =', choices: ['30°', '45°', '60°', '90°'], correctIndex: 1, explanation: 'sin⁻¹(√2/2) = <strong>45°</strong>.' },
                    { question: 'tan θ = √3. θ =', choices: ['30°', '45°', '60°', '90°'], correctIndex: 2, explanation: 'tan⁻¹(√3) = <strong>60°</strong>.' },
                    { question: 'The range of sin⁻¹(x) is:', choices: ['[0°, 180°]', '[−90°, 90°]', '[0°, 360°]', '[−180°, 180°]'], correctIndex: 1, explanation: 'arcsin outputs angles in <strong>[−90°, 90°]</strong>.' },
                ]}
            ]},

            // ---- 5. Degrees & Radians ----
            { id: 'degrees-radians', title: 'Degrees & Radians', subtitle: 'Converting between angle units', xpReward: 40, sections: [
                { type: 'text', content: `<h3>A New Way to Measure Angles</h3><p>You already know degrees — 360° makes a full circle. But in higher math and science, angles are often measured in <strong>radians</strong>, a unit that makes many formulas much cleaner.</p><p>Here's the intuition: imagine a circle with radius r. If you walk along the edge a distance equal to r, the angle you've swept is exactly <strong>1 radian</strong>. It's defined by the arc, not by an arbitrary 360-degree convention.</p><p>Since the full circumference of a circle is 2πr, and a full turn covers 2π radii-worth of arc, one full revolution = <strong>2π radians = 360°</strong>. Halve that and you get: <strong>π radians = 180°</strong>. That's the key conversion fact.</p><h3>Converting Between Degrees and Radians</h3><p>• <strong>Degrees → Radians:</strong> multiply by π/180<br>• <strong>Radians → Degrees:</strong> multiply by 180/π</p><p>Memory trick: if you're going <em>to</em> radians, multiply by π and divide by 180. Going <em>to</em> degrees, multiply by 180 and divide by π.</p><p><strong>Common values to memorize:</strong><br>0° = 0 &nbsp;|&nbsp; 30° = π/6 &nbsp;|&nbsp; 45° = π/4 &nbsp;|&nbsp; 60° = π/3<br>90° = π/2 &nbsp;|&nbsp; 180° = π &nbsp;|&nbsp; 270° = 3π/2 &nbsp;|&nbsp; 360° = 2π</p>` },
                { type: 'interactive_steps', title: 'Guided: Convert 240° to radians', description: 'Multiply by the conversion factor π/180.', steps: [
                    { text: 'Formula: radians = degrees × π/{blank}', answer: '180', hint: 'π radians = 180°' },
                    { text: '240 × π/180 = {blank}π/180', answer: '240', hint: 'Write the numerator' },
                    { text: 'Simplify 240/180: divide both by 60 → {blank}/3', answer: '4', hint: '240 ÷ 60 = ?, 180 ÷ 60 = 3' },
                    { text: '240° = {blank}π/3 radians', answer: '4', hint: '4π/3' }
                ], result: '240° = 4π/3 radians' },
                { type: 'generated_practice', generators: ['deg-to-rad', 'rad-to-deg'] },
                { type: 'practice', problems: [
                    { question: 'Convert 60° to radians:', choices: ['π/6', 'π/4', 'π/3', 'π/2'], correctIndex: 2, explanation: '60 × π/180 = <strong>π/3</strong>.' },
                    { type: 'fill_in', question: 'Convert 90° to radians: ?π/2 (enter the numerator)', answer: '1', explanation: '90 × π/180 = π/2. Numerator = <strong>1</strong>' },
                    { question: 'Convert π/4 to degrees:', choices: ['30°', '45°', '60°', '90°'], correctIndex: 1, explanation: '(π/4) × 180/π = <strong>45°</strong>.' },
                    { type: 'fill_in', question: 'Convert 2π/3 radians to degrees: ?°', answer: '120', explanation: '(2π/3) × (180/π) = 2 × 60 = <strong>120°</strong>' },
                    { question: '2π radians equals:', choices: ['180°', '270°', '360°', '90°'], correctIndex: 2, explanation: '2π × 180/π = <strong>360°</strong>.' },
                ]}
            ]},

            // ---- 6. Unit Circle Basics ----
            { id: 'unit-circle', title: 'The Unit Circle', subtitle: 'Coordinates and trig values', xpReward: 50, sections: [
                { type: 'text', content: `<h3>The Unit Circle</h3><p>The <strong>unit circle</strong> is a circle with radius <strong>1</strong> centered at the origin of the coordinate plane. It's one of the most powerful tools in all of trigonometry — once you understand it, you can read off sin and cos for any angle without a calculator.</p><p>Here's the key insight: for any angle θ (measured from the positive x-axis, going counter-clockwise), the point where the terminal side of the angle meets the unit circle has coordinates exactly equal to <strong>(cos θ, sin θ)</strong>.</p><p>In other words: <strong>x = cos θ</strong> and <strong>y = sin θ</strong>. Always. For any angle, on a unit circle.</p><p>Why? Because cos and sin were defined as adjacent/hypotenuse and opposite/hypotenuse in a right triangle — and on the unit circle, the hypotenuse is always 1, so those ratios simplify to just the x and y coordinates.</p><h3>Key Coordinates to Memorize</h3><p><strong>Axes:</strong> 0° → (1, 0) &nbsp;|&nbsp; 90° → (0, 1) &nbsp;|&nbsp; 180° → (−1, 0) &nbsp;|&nbsp; 270° → (0, −1)</p><p><strong>Special angles:</strong><br>30° → (√3/2, 1/2) &nbsp;|&nbsp; 45° → (√2/2, √2/2) &nbsp;|&nbsp; 60° → (1/2, √3/2)</p><p>Notice the pattern: as θ goes from 0° to 90°, sin (y) grows from 0 to 1 while cos (x) shrinks from 1 to 0.</p>` },
                { type: 'generated_practice', generators: ['unit-circle-coords', 'quadrant-id'] },
                { type: 'tips', content: `<h4>💡 Key Takeaways</h4><p><strong>x-coordinate = cos θ, y-coordinate = sin θ.</strong> This is the heart of the unit circle.</p><p>A useful memory trick for the 30-60-90 values: the y-coordinates (sines) for 30°, 45°, 60° are √1/2, √2/2, √3/2 — the numerators go 1, √2, √3 under the root, divided by 2.</p>` },
                { type: 'practice', problems: [
                    { question: 'On the unit circle, the x-coordinate represents:', choices: ['sin θ', 'cos θ', 'tan θ', 'sec θ'], correctIndex: 1, explanation: 'x = <strong>cos θ</strong>.' },
                    { question: 'cos 90° =', choices: ['1', '0', '−1', '√2/2'], correctIndex: 1, explanation: 'At 90°, the point is (0,1). cos 90° = <strong>0</strong>.' },
                    { question: 'sin 30° =', choices: ['√3/2', '1/2', '√2/2', '1'], correctIndex: 1, explanation: 'sin 30° = <strong>1/2</strong>.' },
                    { question: 'The unit circle has radius:', choices: ['0', '1', '2', 'π'], correctIndex: 1, explanation: 'The unit circle has radius <strong>1</strong>.' },
                ]}
            ]},

            // ---- 7. Reference Angles ----
            { id: 'reference-angles', title: 'Reference Angles', subtitle: 'Finding trig values in any quadrant', xpReward: 45, sections: [
                { type: 'text', content: `<h3>What is a Reference Angle?</h3><p>The trig values for 30°, 45°, and 60° are easy to memorize. But what about 150°, 225°, or 330°? Reference angles let you reuse those known values for any angle.</p><p>A <strong>reference angle</strong> is the positive acute angle (between 0° and 90°) between the terminal side of your angle and the nearest part of the x-axis. Think of it as "how far is this angle from horizontal?"</p><p>To find the reference angle from an angle θ in standard position:<br>• <strong>Q1 (0°–90°):</strong> reference = θ (it's already acute)<br>• <strong>Q2 (90°–180°):</strong> reference = 180° − θ<br>• <strong>Q3 (180°–270°):</strong> reference = θ − 180°<br>• <strong>Q4 (270°–360°):</strong> reference = 360° − θ</p><h3>Which Quadrant? Use ASTC</h3><p>Once you have the reference angle's trig value, you need to decide whether the answer is positive or negative. The mnemonic <strong>ASTC</strong> tells you which functions are <em>positive</em> in each quadrant (all others are negative):</p><p>• <strong>Q1: A</strong>ll — sin, cos, and tan are all positive.<br>• <strong>Q2: S</strong>in — only sin (and its reciprocal csc) is positive.<br>• <strong>Q3: T</strong>an — only tan (and its reciprocal cot) is positive.<br>• <strong>Q4: C</strong>os — only cos (and its reciprocal sec) is positive.</p><p>Memory phrase: <em>"<strong>A</strong>ll <strong>S</strong>tudents <strong>T</strong>ake <strong>C</strong>alculus"</em> — one letter per quadrant, going counter-clockwise from Q1.</p>` },
                { type: 'interactive_steps', title: 'Guided: Find sin(210°) using reference angles', description: 'Find the reference angle, then apply the quadrant sign.', steps: [
                    { text: '210° is in Quadrant {blank}', answer: '3', hint: '180° < 210° < 270°' },
                    { text: 'Reference angle = 210° − 180° = {blank}°', answer: '30', hint: 'For Q3: ref = θ − 180°' },
                    { text: 'sin(30°) = {blank}', answer: '0.5', hint: 'Special angle value' },
                    { text: 'In Q3, sin is negative (only Tan is positive in Q3). So sin(210°) = {blank}', answer: '-0.5', hint: 'Apply the negative sign' }
                ], result: 'sin(210°) = −0.5' },
                { type: 'generated_practice', generators: ['find-reference-angle', 'trig-with-reference'] },
                { type: 'practice', problems: [
                    { type: 'fill_in', question: 'Reference angle for 150°: ?°', answer: '30', explanation: '180° − 150° = <strong>30°</strong>' },
                    { type: 'fill_in', question: 'Reference angle for 225°: ?°', answer: '45', explanation: '225° − 180° = <strong>45°</strong>' },
                    { type: 'fill_in', question: 'Reference angle for 315°: ?°', answer: '45', explanation: '360° − 315° = <strong>45°</strong>' },
                    { question: 'In which quadrants is sin θ positive?', choices: ['Q1 and Q2', 'Q1 and Q4', 'Q2 and Q3', 'Q3 and Q4'], correctIndex: 0, explanation: 'ASTC: A (all) and S (sin) → sin is positive in <strong>Q1 and Q2</strong>.' },
                ]}
            ]},

            // ---- 8. Reciprocal Trig Functions ----
            { id: 'reciprocal-trig', title: 'Reciprocal Trig Functions', subtitle: 'csc, sec, and cot', xpReward: 45, sections: [
                { type: 'text', content: `<h3>The Three Reciprocal Functions</h3><p>Each of the three main trig functions (sin, cos, tan) has a reciprocal — a function equal to 1 divided by it. These come up frequently in advanced trig and calculus.</p><p>• <strong>csc θ = 1/sin θ</strong> (cosecant — the reciprocal of sine)<br>• <strong>sec θ = 1/cos θ</strong> (secant — the reciprocal of cosine)<br>• <strong>cot θ = 1/tan θ = cos θ/sin θ</strong> (cotangent — the reciprocal of tangent)</p><p>Memory trick: the reciprocal pairs have <em>co-functions</em> matching across: sine pairs with <strong>co</strong>secant, <strong>co</strong>sine pairs with secant, and <strong>co</strong>tangent pairs with tangent. (Each pair has exactly one "co" prefix.)</p><h3>When Are They Undefined?</h3><p>A reciprocal is undefined whenever its denominator equals zero:</p><p>• <strong>csc θ</strong> is undefined when sin θ = 0 (at 0°, 180°, 360°, ...)<br>• <strong>sec θ</strong> is undefined when cos θ = 0 (at 90°, 270°, ...)<br>• <strong>cot θ</strong> is undefined when sin θ = 0 (same as csc)</p><p>To evaluate a reciprocal function, just find the original function first and flip it. If sin θ = 3/5, then csc θ = 5/3.</p>` },
                { type: 'generated_practice', generators: ['reciprocal-trig-eval'] },
                { type: 'practice', problems: [
                    { question: 'csc θ if sin θ = 3/5:', choices: ['5/3', '3/5', '4/5', '5/4'], correctIndex: 0, explanation: 'csc = 1/sin = <strong>5/3</strong>.' },
                    { question: 'sec θ if cos θ = 1/2:', choices: ['1/2', '2', '√3', '√3/2'], correctIndex: 1, explanation: 'sec = 1/cos = 1/(1/2) = <strong>2</strong>.' },
                    { question: 'cot 45° =', choices: ['0', '1', '√2', 'undefined'], correctIndex: 1, explanation: 'tan 45° = 1, so cot 45° = 1/1 = <strong>1</strong>.' },
                    { question: 'sec 90° is:', choices: ['0', '1', '−1', 'Undefined'], correctIndex: 3, explanation: 'cos 90° = 0, so sec 90° = 1/0 = <strong>undefined</strong>.' },
                ]}
            ]},

            // ---- 9. Pythagorean Identities ----
            { id: 'pythagorean-identities', title: 'Pythagorean Identities', subtitle: 'Fundamental trig relationships', xpReward: 45, sections: [
                { type: 'text', content: `<h3>The Three Pythagorean Identities</h3><p>On the unit circle, any point (x, y) = (cos θ, sin θ) lies at distance 1 from the origin. The distance formula gives x² + y² = 1, so substituting:</p><p style="text-align:center;"><strong>sin²θ + cos²θ = 1</strong></p><p>This is the most important identity in trig — it holds for every possible angle, not just right triangle angles. (Note: sin²θ is shorthand for (sin θ)².)</p><p>From this one identity, two more follow by dividing both sides by different things:</p><p><strong>Divide both sides by cos²θ:</strong><br>sin²θ/cos²θ + 1 = 1/cos²θ<br>→ <strong>tan²θ + 1 = sec²θ</strong></p><p><strong>Divide both sides by sin²θ:</strong><br>1 + cos²θ/sin²θ = 1/sin²θ<br>→ <strong>1 + cot²θ = csc²θ</strong></p><p>These three identities are your go-to tools for simplifying and proving trig expressions. You'll use the first one most often.</p>` },
                { type: 'generated_practice', generators: ['pythagorean-identity', 'reciprocal-identity'] },
                { type: 'practice', problems: [
                    { question: 'sin²θ + cos²θ =', choices: ['0', '1', '2', 'sin θ cos θ'], correctIndex: 1, explanation: 'The fundamental identity: <strong>1</strong>.' },
                    { question: 'If sin θ = 3/5, then cos²θ =', choices: ['4/25', '16/25', '9/25', '7/25'], correctIndex: 1, explanation: 'cos²θ = 1 − sin²θ = 1 − 9/25 = <strong>16/25</strong>.' },
                    { question: 'tan²θ + 1 =', choices: ['csc²θ', 'sec²θ', 'cot²θ', 'sin²θ'], correctIndex: 1, explanation: 'tan²θ + 1 = <strong>sec²θ</strong>.' },
                    { question: 'If cos θ = 5/13, find sin θ (θ in Q1):', choices: ['12/13', '8/13', '5/12', '1/13'], correctIndex: 0, explanation: 'sin²θ = 1 − 25/169 = 144/169. sin θ = <strong>12/13</strong>.' },
                ]}
            ]},

            // ---- 10. Graphing sin & cos ----
            { id: 'graphing-sin-cos', title: 'Graphing sin & cos', subtitle: 'Amplitude, period, and shifts', xpReward: 50, sections: [
                { type: 'text', content: `<h3>The General Sinusoidal Form</h3><p>The basic sin and cos graphs are smooth, repeating waves. The general form packs four adjustable parameters into one equation:</p><p style="text-align:center;"><strong>y = A sin(Bx + C) + D</strong></p><p>Each parameter controls a different feature of the wave:</p><p><strong>A — Amplitude = |A|</strong><br>The amplitude is the height from the centre line to the peak (or depth to the trough). If A = 3, the wave reaches up to 3 and down to −3 from its midline.<br>⚠️ If A is <em>negative</em> (e.g., y = −3 sin x), the wave is <strong>flipped upside down</strong> (reflected over the x-axis) — but the amplitude is still |−3| = 3, not −3.</p><p><strong>B — Period = 2π/|B|</strong><br>The period is how long one full cycle takes. The larger B is, the faster the wave oscillates, and the shorter each cycle. Default period (B=1) is 2π; doubling B halves the period to π.</p><p><strong>Phase Shift (h-form)</strong><br>To make phase shifts intuitive, rewrite the equation as: y = A sin(B(x − h)) + D, where h is the phase shift. If h &gt; 0, the graph shifts <strong>RIGHT</strong> by h units. If h &lt; 0, the graph shifts <strong>LEFT</strong> by |h| units. For example, y = sin(x − π/2) shifts the graph right by π/2, while y = sin(x + π/3) shifts it left by π/3 (because h = −π/3). To find h from the form y = A sin(Bx + C) + D, factor out B from the argument: Bx + C = B(x + C/B), so h = −C/B.</p><p><strong>D — Vertical Shift</strong><br>D moves the entire graph up (if positive) or down (if negative). The midline of the wave becomes y = D instead of y = 0.</p>` },
                { type: 'generated_practice', generators: ['trig-amplitude', 'trig-period'] },
                { type: 'practice', problems: [
                    { question: 'Amplitude of y = 3 sin(x):', choices: ['1', '3', '6', 'π'], correctIndex: 1, explanation: 'Amplitude = |A| = <strong>3</strong>.' },
                    { question: 'Period of y = sin(2x):', choices: ['π', '2π', '4π', 'π/2'], correctIndex: 0, explanation: 'Period = 2π/|B| = 2π/2 = <strong>π</strong>.' },
                    { question: 'Vertical shift of y = cos(x) + 5:', choices: ['0', '1', '5', '−5'], correctIndex: 2, explanation: 'D = <strong>5</strong> (shifts the graph up 5 units).' },
                    { question: 'The graph of y = −sin(x) is a reflection over:', choices: ['y-axis', 'x-axis', 'Line y = 1', 'Origin'], correctIndex: 1, explanation: 'A negative A flips the wave over the <strong>x-axis</strong>.' },
                    { question: 'In y = 2sin(x − π/4) + 1, the phase shift is:', choices: ['π/4 left', 'π/4 right', 'π/2 right', '−1 left'], correctIndex: 1, explanation: 'Written as A sin(B(x − h)) + D, h = π/4 → the graph shifts <strong>π/4 right</strong>.' },
                ]}
            ]},

            // ---- 11. Graphing tan & Reciprocals ----
            { id: 'graphing-tan', title: 'Graphing tan & Reciprocals', subtitle: 'Asymptotes and behavior', xpReward: 45, sections: [
                { type: 'text', content: `<h3>The Tangent Graph</h3><p>The graph of y = tan(x) looks very different from sine and cosine — instead of smooth waves, it has vertical lines it can never cross called <strong>asymptotes</strong>.</p><p>Why? Because tan = sin/cos. Whenever cos x = 0 (at x = π/2, 3π/2, ..., or equivalently x = π/2 + nπ for any integer n), you'd be dividing by zero — which is undefined. The graph shoots off to +∞ or −∞ on either side of those points.</p><p>Key features of y = tan(x):</p><p>• <strong>Period: π</strong> (not 2π! — one full cycle repeats every π units).<br>• <strong>Vertical asymptotes</strong> at x = π/2 + nπ (wherever cos x = 0).<br>• <strong>Range: (−∞, ∞)</strong> — it takes every real value within each cycle.<br>• Passes through the origin (0, 0) and increases from left to right within each cycle.</p><h3>Graphs of csc and sec</h3><p>Since csc = 1/sin and sec = 1/cos, their graphs are built by "flipping" the sine and cosine graphs:</p><p>• <strong>csc x</strong> has vertical asymptotes where sin x = 0 (at x = 0, π, 2π, ...) and forms upward and downward U-curves between them.<br>• <strong>sec x</strong> has vertical asymptotes where cos x = 0 (at x = π/2, 3π/2, ...) and forms similar U-curves.</p><p>Both csc and sec have ranges of (−∞, −1] ∪ [1, ∞) — they never land between −1 and 1.</p>` },
                { type: 'generated_practice', generators: ['trig-period-tan', 'trig-asymptote'] },
                { type: 'practice', problems: [
                    { question: 'The period of y = tan(x) is:', choices: ['π', '2π', 'π/2', '4π'], correctIndex: 0, explanation: 'tan has period <strong>π</strong>.' },
                    { question: 'tan(x) has vertical asymptotes where:', choices: ['sin x = 0', 'cos x = 0', 'tan x = 0', 'sin x = 1'], correctIndex: 1, explanation: 'tan = sin/cos, so asymptotes where <strong>cos x = 0</strong>.' },
                    { question: 'The range of y = tan(x) is:', choices: ['[−1, 1]', '(0, ∞)', '(−∞, ∞)', '[0, 2π]'], correctIndex: 2, explanation: 'tan takes all real values: <strong>(−∞, ∞)</strong>.' },
                    { question: 'csc(x) is undefined when:', choices: ['cos x = 0', 'sin x = 0', 'tan x = 0', 'sin x = 1'], correctIndex: 1, explanation: 'csc = 1/sin, undefined when <strong>sin x = 0</strong>.' },
                ]}
            ]},

            // ---- 12. Solving Basic Trig Equations ----
            { id: 'trig-equations', title: 'Solving Trig Equations', subtitle: 'Finding all solutions', xpReward: 50, sections: [
                { type: 'text', content: `<h3>Finding All Solutions to a Trig Equation</h3><p>Solving a trig equation like sin θ = ½ is different from solving an algebra equation, because trig functions repeat — infinitely many angles can satisfy the same equation. Here's a reliable three-step approach:</p><p><strong>Step 1 — Find the reference angle.</strong> Use inverse trig to find the basic angle: sin⁻¹(½) = 30°. This is your reference angle.</p><p><strong>Step 2 — Find all solutions in one full revolution (0° to 360°).</strong> Use ASTC to decide which quadrants give the correct sign:<br>• sin is positive in Q1 and Q2 → θ = 30° and θ = 180° − 30° = 150°<br>• cos is positive in Q1 and Q4<br>• tan is positive in Q1 and Q3</p><p><strong>Step 3 — Add the general solution for all rotations.</strong> Since the pattern repeats every 360°, the full solution set is θ = 30° + 360°n and θ = 150° + 360°n, where <strong>n is any integer</strong> (0, ±1, ±2, ...). This notation captures every possible solution at once.</p>` },
                { type: 'generated_practice', generators: ['solve-trig-eq-basic'] },
                { type: 'text', content: `<h3>Equations Requiring Algebraic Techniques</h3><p>Some trig equations look like <strong>quadratic equations in disguise</strong>. For example, 2sin²x − sinx − 1 = 0 has the same structure as 2u² − u − 1 = 0. Let u = sin x to get 2u² − u − 1 = 0. Factor: (2u + 1)(u − 1) = 0, so u = −½ or u = 1, giving sin x = −½ or sin x = 1. Then solve each equation separately: sin x = −½ → x = 210° or 330°; sin x = 1 → x = 90°.</p><p>Similarly, equations like cos²x = 1 − sin²x can be solved by <strong>substituting a Pythagorean identity</strong> to convert everything to one trig function. For example, cos²x − sinx = 1: substitute cos²x = 1 − sin²x to get 1 − sin²x − sinx = 1 → −sin²x − sinx = 0 → −sinx(sinx + 1) = 0. Then solve: sinx = 0 or sinx = −1.</p>` },
                { type: 'generated_practice', generators: ['trig-eq-quadratic'] },
                { type: 'practice', problems: [
                    { question: 'cos θ = 0. Solutions in [0°, 360°):', choices: ['0°, 180°', '90°, 270°', '0°, 360°', '45°, 225°'], correctIndex: 1, explanation: 'cos = 0 at <strong>90° and 270°</strong>.' },
                    { question: 'sin θ = −1. Solution in [0°, 360°):', choices: ['90°', '180°', '270°', '360°'], correctIndex: 2, explanation: 'sin = −1 at <strong>270°</strong> (bottom of unit circle).' },
                    { question: 'tan θ = 1. Solutions in [0°, 360°):', choices: ['45° only', '45° and 225°', '45° and 135°', '225° only'], correctIndex: 1, explanation: 'tan = 1 at <strong>45° and 225°</strong> (Q1 and Q3).' },
                    { question: 'How many solutions does sin θ = 0.5 have in [0°, 360°)?', choices: ['1', '2', '3', '4'], correctIndex: 1, explanation: 'Sin = 0.5 at 30° and 150° → <strong>2</strong> solutions.' },
                    { question: '2sin²x − sinx − 1 = 0. Factor as (2sinx + 1)(sinx − 1) = 0. Solutions in [0°,360°):', choices: ['30°, 150°, 270°', '210°, 330°, 90°', '90°, 210°, 330°', 'No solution'], correctIndex: 1, explanation: 'sin x = −½ → 210°, 330°. sin x = 1 → 90°. Solutions: <strong>90°, 210°, 330°</strong>.' },
                    { question: 'cos²x − sinx = 1 in [0°,360°). Substitute cos²x = 1 − sin²x:', choices: ['0°, 180°', '0°, 180°, 270°', '90°, 270°', '270° only'], correctIndex: 1, explanation: 'Substituting: 1−sin²x − sinx = 1 → −sinx(sinx+1) = 0. sin x = 0 → 0°, 180°; sin x = −1 → 270°. Answer: <strong>0°, 180°, 270°</strong>.' },
                ]}
            ]},

            // ---- 13. Law of Sines ----
            { id: 'law-of-sines', title: 'Law of Sines', subtitle: 'Solving non-right triangles', xpReward: 50, sections: [
                { type: 'text', content: `<h3>Beyond Right Triangles</h3><p>SOH-CAH-TOA only works for right triangles. For triangles with no right angle, we need more general tools. The <strong>Law of Sines</strong> is the first of two.</p><p>Label the triangle so that side <em>a</em> is opposite angle A, side <em>b</em> is opposite angle B, and side <em>c</em> is opposite angle C. The Law of Sines says all three of these ratios are equal:</p><p style="text-align:center; font-size:1.1em;"><strong>a / sin A = b / sin B = c / sin C</strong></p><p>You only need to use two of the three ratios at a time — pick the pair where you know three of the four values and can solve for the fourth.</p><p><strong>When to use it:</strong><br>• <strong>AAS</strong> — two angles and a non-included side<br>• <strong>ASA</strong> — two angles and the side between them<br>• <strong>SSA</strong> — two sides and a non-included angle (watch out — this is the ambiguous case!)</p><p><strong>Important limit:</strong> If you know all three angles but no side lengths, you <em>cannot</em> find actual side lengths. Why? Because infinitely many triangles can have the same three angles (they're all similar to each other but different sizes). You need at least one side to "anchor" the size.</p>` },
                { type: 'example', title: 'Finding a Side', content: `<p><strong>A = 40°, B = 60°, a = 8. Find b.</strong></p><p>First find C: C = 180° − 40° − 60° = 80°.</p><p>Set up the proportion: b/sin 60° = 8/sin 40°</p><p>Cross-multiply: b = 8 × sin 60° / sin 40° ≈ 8 × 0.866 / 0.643 ≈ <strong>10.78</strong>.</p>` },
                { type: 'interactive_steps', title: 'Guided: A = 35°, B = 70°, a = 10. Find b.', description: 'Set up and solve using the Law of Sines.', steps: [
                    { text: 'First, find C: 180° − 35° − 70° = {blank}°', answer: '75', hint: 'Angles in a triangle sum to 180°' },
                    { text: 'Set up the proportion: a/sin A = b/sin B → 10/sin 35° = b/sin {blank}°', answer: '70', hint: 'We want to find b, which is opposite angle B' },
                    { text: 'Cross multiply: b = 10 · sin 70° / sin {blank}°', answer: '35', hint: 'sin A = sin 35°' },
                    { text: 'sin 70° ≈ 0.940, sin 35° ≈ 0.574. b ≈ 10 × 0.940 / 0.574 ≈ {blank}', answer: '16.4', hint: '9.40 ÷ 0.574 ≈ ?' }
                ], result: 'b ≈ 16.4' },
                { type: 'generated_practice', generators: ['law-of-sines-calc'] },
                { type: 'tips', content: `<h4>💡 Law of Sines vs Law of Cosines</h4><p>Use <strong>Law of Sines</strong> when you have: AAS, ASA, or SSA.</p><p>Use <strong>Law of Cosines</strong> when you have: SAS or SSS.</p><p><strong>Watch out:</strong> SSA can give 0, 1, or 2 triangles (the ambiguous case)!</p>` },
                { type: 'practice', problems: [
                    { question: 'When is Law of Sines most useful?', choices: ['SAS', 'SSS', 'AAS or ASA', 'Right triangles only'], correctIndex: 2, explanation: 'Law of Sines excels with <strong>AAS or ASA</strong> configurations.' },
                    { question: 'In the Law of Sines, each ratio is:', choices: ['side/side', 'angle/angle', 'side/sin(opposite angle)', 'sin(angle)/sin(angle)'], correctIndex: 2, explanation: 'Each ratio is <strong>side / sin(opposite angle)</strong>.' },
                    { question: 'A = 30°, a = 5, B = 45°. Find b.', choices: ['5 sin 45°/sin 30°', '5 sin 30°/sin 45°', '5 cos 45°/sin 30°', '5/sin 30°'], correctIndex: 0, explanation: 'b = a sin B / sin A = <strong>5 sin 45° / sin 30°</strong>.' },
                    { question: 'If you know all three angles but no sides, can you find side lengths?', choices: ['Yes', 'No', 'Only the longest', 'Only ratios'], correctIndex: 1, explanation: '<strong>No</strong> — you need at least one side to find actual lengths. Infinitely many differently-sized triangles can share the same three angles.' },
                ]}
            ]},

            // ---- 14. Law of Cosines ----
            { id: 'law-of-cosines', title: 'Law of Cosines', subtitle: 'The generalized Pythagorean theorem', xpReward: 50, sections: [
                { type: 'text', content: `<h3>The Law of Cosines</h3><p>When you have <strong>SAS</strong> (two sides and the angle between them) or <strong>SSS</strong> (all three sides), the Law of Sines won't work — you need the <strong>Law of Cosines</strong>.</p><p>For a triangle with sides a, b, c and their opposite angles A, B, C:</p><p style="text-align:center; font-size:1.1em;"><strong>c² = a² + b² − 2ab cos C</strong></p><p>Notice: if C = 90°, then cos 90° = 0 and the formula becomes c² = a² + b² — the Pythagorean theorem! The Law of Cosines is its generalisation for any triangle.</p><h3>Finding an Angle from Three Known Sides (SSS)</h3><p>You can rearrange the formula to solve for a missing angle. Solving for angle C:</p><p style="text-align:center;"><strong>cos C = (a² + b² − c²) / (2ab)</strong></p><p>Then use cos⁻¹ to find the angle: C = cos⁻¹((a² + b² − c²) / (2ab)).</p><p>You can write similar versions for angles A and B by cycling the letters.</p>` },
                { type: 'interactive_steps', title: 'Guided: a = 8, b = 5, C = 60°. Find c.', description: 'Apply c² = a² + b² − 2ab cos C.', steps: [
                    { text: 'a² = 8² = {blank}', answer: '64', hint: '8 × 8' },
                    { text: 'b² = 5² = {blank}', answer: '25', hint: '5 × 5' },
                    { text: '2ab = 2 × 8 × 5 = {blank}', answer: '80', hint: 'Multiply' },
                    { text: 'cos 60° = {blank}', answer: '0.5', hint: 'Special angle value' },
                    { text: 'c² = 64 + 25 − 80(0.5) = 89 − {blank}', answer: '40', hint: '80 × 0.5' },
                    { text: 'c² = {blank}', answer: '49', hint: '89 − 40' },
                    { text: 'c = √49 = {blank}', answer: '7', hint: 'Perfect square!' }
                ], result: 'c = 7' },
                { type: 'generated_practice', generators: ['law-of-cosines-calc', 'law-choice'] },
                { type: 'practice', problems: [
                    { question: 'When is Law of Cosines most useful?', choices: ['AAS', 'ASA', 'SAS or SSS', 'AAA'], correctIndex: 2, explanation: 'Law of Cosines is ideal for <strong>SAS or SSS</strong>.' },
                    { question: 'a=5, b=7, C=60°. Find c².', choices: ['74 − 70cos60°', '74 + 70cos60°', '74 − 35', '12 − 70cos60°'], correctIndex: 0, explanation: 'c² = 25 + 49 − 2(5)(7)cos60° = <strong>74 − 70cos60°</strong>.' },
                    { question: 'If C = 90°, the Law of Cosines becomes:', choices: ['Law of Sines', 'c² = a² + b²', 'c² = a² − b²', 'c = a + b'], correctIndex: 1, explanation: 'cos 90° = 0, so <strong>c² = a² + b²</strong> (Pythagorean theorem).' },
                    { question: 'To find an angle from three known sides, use:', choices: ['Law of Sines', 'Law of Cosines', 'Pythagorean theorem', 'SOHCAHTOA'], correctIndex: 1, explanation: 'With SSS, rearrange Law of Cosines: cos C = (a² + b² − c²)/(2ab), then use cos⁻¹. Use <strong>Law of Cosines</strong>.' },
                ]}
            ]},

            // ---- 15. Ambiguous Case (SSA) ----
            { id: 'ambiguous-case', title: 'The Ambiguous Case', subtitle: 'SSA and how many triangles form', xpReward: 50, sections: [
                { type: 'text', content: `<h3>SSA — Why It's Tricky</h3><p>Normally when you have enough information to describe a triangle, exactly one triangle is possible. But with <strong>SSA</strong> (two sides and an angle that is <em>not</em> between them), things get weird — there might be 0, 1, or 2 valid triangles. That's why SSA is called the <strong>ambiguous case</strong>.</p><p>Imagine swinging the opposite side like a pendulum: depending on its length, it might not reach the base (0 triangles), touch it at exactly one point (1 triangle), or cross it at two points (2 triangles).</p><p>The key comparison is between side <em>a</em> (opposite the given angle A) and the <strong>height</strong> h = b sin A (the "minimum length" needed to form a triangle):</p><p>• <strong>a &lt; h</strong> → <strong>0 triangles</strong> — side a is too short to reach the base.<br>• <strong>a = h</strong> → <strong>1 triangle</strong> — a exactly reaches the base, forming a right triangle.<br>• <strong>h &lt; a &lt; b</strong> → <strong>2 triangles</strong> — a swings to two different positions.<br>• <strong>a ≥ b</strong> → <strong>1 triangle</strong> — a is long enough that only one position is possible.</p>` },
                { type: 'generated_practice', generators: ['ambiguous-case-count'] },
                { type: 'practice', problems: [
                    { question: 'SSA is called the "ambiguous case" because:', choices: ['It always gives 2 answers', 'It might give 0, 1, or 2 triangles', 'The angles are unknown', 'It requires a calculator'], correctIndex: 1, explanation: 'SSA can produce <strong>0, 1, or 2</strong> possible triangles.' },
                    { question: 'A=30°, b=10, a=5. How many triangles? (h = 10 sin 30° = 5)', choices: ['0', '1', '2', 'Cannot determine'], correctIndex: 1, explanation: 'a = h = 5, so exactly <strong>1</strong> right triangle.' },
                    { question: 'A=30°, b=10, a=3. How many triangles? (h = 5)', choices: ['0', '1', '2', 'Infinite'], correctIndex: 0, explanation: 'a = 3 < h = 5, so <strong>0</strong> triangles.' },
                    { question: 'A=30°, b=10, a=7. How many triangles? (h = 5)', choices: ['0', '1', '2', 'Infinite'], correctIndex: 2, explanation: 'h < a < b (5 < 7 < 10), so <strong>2</strong> triangles.' },
                ]}
            ]},

            // ---- 16. Area of a Triangle (Trig) ----
            { id: 'triangle-area-trig', title: 'Triangle Area with Trig', subtitle: 'Using sine to find area', xpReward: 40, sections: [
                { type: 'text', content: `<h3>A Better Area Formula</h3><p>You already know Area = ½ × base × height. But finding the height requires a separate calculation — and sometimes you're not given it. When you know <strong>two sides and the angle between them (SAS)</strong>, there's a direct shortcut.</p><p>The derivation: if you drop a perpendicular from a vertex to make a height h, then h = a sin C (from basic trig in the right triangle formed). Substituting into ½ × base × height:</p><p style="text-align:center; font-size:1.1em;"><strong>Area = ½ ab sin C</strong></p><p>where a and b are any two sides and C is the angle <em>between</em> them (the "included angle").</p><p>This works for <em>any</em> triangle — not just right triangles. Two special cases worth noting:<br>• If C = 90°, then sin 90° = 1 and the formula becomes ½ab — the familiar right triangle formula.<br>• If C = 0° or 180°, then sin C = 0 and the area is 0 (the triangle degenerates to a flat line).</p>` },
                { type: 'example', title: 'Finding Area', content: `<p><strong>Given: a = 8, b = 6, C = 30°.</strong></p><p>Area = ½ × 8 × 6 × sin 30° = 24 × 0.5 = <strong>12</strong></p>` },
                { type: 'interactive_steps', title: 'Guided: Find area when a = 10, b = 7, C = 60°', description: 'Plug into the formula step by step.', steps: [
                    { text: 'Area = ½ · a · b · sin C = ½ · 10 · {blank} · sin 60°', answer: '7', hint: 'b = 7' },
                    { text: '½ · 10 · 7 = {blank}', answer: '35', hint: '10 × 7 ÷ 2' },
                    { text: 'sin 60° = √3/2 ≈ {blank}', answer: '0.866', hint: 'Recall the special angle value' },
                    { text: 'Area = 35 × 0.866 ≈ {blank}', answer: '30.3', hint: '35 × 0.866 ≈ ?' }
                ], result: 'Area ≈ 30.3 square units' },
                { type: 'generated_practice', generators: ['triangle-area-trig'] },
                { type: 'tips', content: `<h4>💡 When to Use This Formula</h4><p>Use Area = ½ab sin C whenever you have <strong>SAS</strong> (two sides and the included angle).</p><p>If C = 90°, sin 90° = 1, and the formula simplifies to the familiar ½bh.</p><p>If C = 0° or 180°, the area is 0 — the triangle degenerates to a line!</p>` },
                { type: 'practice', problems: [
                    { question: 'a=8, b=6, C=30°. Area =', choices: ['12', '24', '48', '6'], correctIndex: 0, explanation: '½(8)(6)sin 30° = 24 × 0.5 = <strong>12</strong>.' },
                    { question: 'a=10, b=10, C=90°. Area =', choices: ['50', '100', '25', '200'], correctIndex: 0, explanation: '½(10)(10)sin 90° = 50 × 1 = <strong>50</strong>.' },
                    { question: 'The formula Area = ½ab sin C requires which piece of info?', choices: ['Three sides', 'Two sides and included angle', 'One side and two angles', 'Three angles'], correctIndex: 1, explanation: 'You need <strong>two sides and the included angle</strong> (SAS).' },
                    { question: 'If C = 0°, the area would be:', choices: ['Maximum', '0', '½ab', 'Undefined'], correctIndex: 1, explanation: 'sin 0° = 0, so area = 0 (the triangle collapses to a line).' },
                ]}
            ]},

            // ---- 17. Sum & Difference Identities ----
            { id: 'sum-difference', title: 'Sum & Difference Identities', subtitle: 'sin(A±B) and cos(A±B)', xpReward: 55, sections: [
                { type: 'text', content: `<h3>Sum & Difference Formulas</h3><p>What's sin(75°)? There's no simple unit circle value for 75°, but we can write it as 45° + 30° — two angles we do know. The sum and difference identities let us expand trig of a combined angle into trig of two simpler ones.</p><p><strong>sin(A + B) = sin A cos B + cos A sin B</strong><br><strong>sin(A − B) = sin A cos B − cos A sin B</strong></p><p><strong>cos(A + B) = cos A cos B − sin A sin B</strong><br><strong>cos(A − B) = cos A cos B + sin A sin B</strong></p><p>Memory tricks:<br>• <strong>Sine:</strong> always a mix of sin and cos, and the ± sign in the formula <em>matches</em> the ± in the angle: sin(A + B) has a +, sin(A − B) has a −.<br>• <strong>Cosine:</strong> always same-function pairs (cos·cos, sin·sin), but the sign <em>flips</em>: cos(A + B) subtracts, cos(A − B) adds.</p><h3>Cofunction Identity</h3><p>One very useful special case of the difference formula: let A = 90° and you get:</p><p style="text-align:center;"><strong>cos(90° − θ) = sin θ</strong> &nbsp; and &nbsp; <strong>sin(90° − θ) = cos θ</strong></p><p>This makes sense geometrically: in a right triangle, the two acute angles add up to 90°, so the sine of one equals the cosine of the other. That's why sin and cos are called <em>cofunctions</em>.</p>` },
                { type: 'example', title: 'Finding sin 75°', content: `<p>sin 75° = sin(45° + 30°) = sin 45° cos 30° + cos 45° sin 30°</p><p>= (√2/2)(√3/2) + (√2/2)(1/2) = √6/4 + √2/4 = <strong>(√6 + √2)/4</strong></p>` },
                { type: 'interactive_steps', title: 'Guided: Find cos 15° using cos(45° − 30°)', description: 'Apply the cosine difference formula.', steps: [
                    { text: 'cos(A − B) = cos A cos B + sin A sin B. Here A = 45°, B = {blank}', answer: '30', hint: '45° − 30° = 15°' },
                    { text: 'cos 45° = √2/2, cos 30° = {blank}', answer: '√3/2', hint: 'Recall the 30-60-90 triangle values' },
                    { text: 'sin 45° = √2/2, sin 30° = {blank}', answer: '1/2', hint: 'sin 30° is the simplest special value' },
                    { text: 'cos45·cos30 = (√2/2)(√3/2) = {blank}', answer: '√6/4', hint: '√2 × √3 = √6, and 2 × 2 = 4' },
                    { text: 'sin45·sin30 = (√2/2)(1/2) = {blank}', answer: '√2/4', hint: '√2 × 1 = √2, denominator = 4' }
                ], result: 'cos 15° = √6/4 + √2/4 = (√6 + √2)/4' },
                { type: 'generated_practice', generators: ['sum-formula-apply'] },
                { type: 'practice', problems: [
                    { question: 'sin(A + B) =', choices: ['sin A sin B + cos A cos B', 'sin A cos B + cos A sin B', 'sin A cos B − cos A sin B', 'cos A cos B − sin A sin B'], correctIndex: 1, explanation: '<strong>sin A cos B + cos A sin B</strong>.' },
                    { question: 'cos(A + B) =', choices: ['cos A cos B − sin A sin B', 'cos A cos B + sin A sin B', 'sin A cos B + cos A sin B', 'sin A sin B − cos A cos B'], correctIndex: 0, explanation: '<strong>cos A cos B − sin A sin B</strong>.' },
                    { question: 'sin 75° = sin(45° + 30°) = ?', choices: ['(√6+√2)/4', '(√6−√2)/4', '(√3+1)/4', '√3/2'], correctIndex: 0, explanation: 'sin45cos30 + cos45sin30 = (√2/2)(√3/2) + (√2/2)(1/2) = <strong>(√6+√2)/4</strong>.' },
                    { question: 'cos(90° − θ) equals:', choices: ['cos θ', 'sin θ', '−sin θ', '−cos θ'], correctIndex: 1, explanation: 'Cofunction identity: cos(90°−θ) = <strong>sin θ</strong>. The sine and cosine of complementary angles are equal.' },
                ]}
            ]},

            // ---- 18. Double-Angle Identities ----
            { id: 'double-angle', title: 'Double-Angle Identities', subtitle: 'sin 2θ and cos 2θ', xpReward: 50, sections: [
                { type: 'text', content: `<h3>Double-Angle Formulas</h3><p>What happens when both angles in a sum formula are the same? You get the <strong>double-angle formulas</strong> — a special case of the sum identities with A = B = θ.</p><p>Plug θ into both slots of sin(A + B):<br>sin(θ + θ) = sin θ cos θ + cos θ sin θ = <strong>2 sin θ cos θ</strong></p><p><strong>sin 2θ = 2 sin θ cos θ</strong></p><p>Similarly, cos(θ + θ) = cos θ cos θ − sin θ sin θ = cos²θ − sin²θ. And since sin²θ + cos²θ = 1, we can substitute to get two alternative forms:</p><p><strong>cos 2θ = cos²θ − sin²θ = 2cos²θ − 1 = 1 − 2sin²θ</strong></p><p>Having three equivalent forms for cos 2θ is useful — you pick the one that matches what you already know:</p><p>• Know only sin θ? Use <strong>cos 2θ = 1 − 2sin²θ</strong><br>• Know only cos θ? Use <strong>cos 2θ = 2cos²θ − 1</strong><br>• Know both? Use <strong>cos 2θ = cos²θ − sin²θ</strong></p><p>There's also a double-angle formula for tan: <strong>tan 2θ = 2tan θ / (1 − tan²θ)</strong>.</p>` },
                { type: 'example', title: 'Using Double-Angle Formulas', content: `<p><strong>Given sin θ = 3/5 and cos θ = 4/5, find sin 2θ and cos 2θ:</strong></p><p>sin 2θ = 2(3/5)(4/5) = 24/25</p><p>cos 2θ = (4/5)² − (3/5)² = 16/25 − 9/25 = <strong>7/25</strong></p>` },
                { type: 'interactive_steps', title: 'Guided: Find cos 2θ if sin θ = 5/13', description: 'Use the identity cos 2θ = 1 − 2sin²θ.', steps: [
                    { text: 'First, find sin²θ: (5/13)² = {blank}', answer: '25/169', hint: 'Square the numerator and denominator separately' },
                    { text: 'Plug into cos 2θ = 1 − 2sin²θ: 1 − 2({blank})', answer: '25/169', hint: 'Use your sin²θ value from step 1' },
                    { text: '2 × 25/169 = {blank}', answer: '50/169', hint: 'Multiply 2 × 25 = 50, keep denominator' },
                    { text: '1 − 50/169 = 169/169 − 50/169 = {blank}', answer: '119/169', hint: '169 − 50 = ?' }
                ], result: 'cos 2θ = 119/169' },
                { type: 'generated_practice', generators: ['trig-double-angle'] },
                { type: 'tips', content: `<h4>💡 Which cos 2θ Form to Use?</h4><p>If you know <strong>only sin θ</strong>, use: cos 2θ = 1 − 2sin²θ.</p><p>If you know <strong>only cos θ</strong>, use: cos 2θ = 2cos²θ − 1.</p><p>If you know <strong>both</strong>, use: cos 2θ = cos²θ − sin²θ.</p>` },
                { type: 'practice', problems: [
                    { question: 'sin 2θ =', choices: ['2 sin θ', '2 sin θ cos θ', 'sin²θ + cos²θ', 'sin θ + cos θ'], correctIndex: 1, explanation: '<strong>2 sin θ cos θ</strong>.' },
                    { question: 'cos 2θ = (choose one form)', choices: ['2cos²θ − 1', '2sin²θ + 1', 'cos θ − sin θ', '2cos θ sin θ'], correctIndex: 0, explanation: '<strong>2cos²θ − 1</strong> (also = cos²θ − sin²θ = 1 − 2sin²θ).' },
                    { question: 'If sin θ = 3/5, cos θ = 4/5, then sin 2θ =', choices: ['6/5', '24/25', '7/25', '12/25'], correctIndex: 1, explanation: 'sin 2θ = 2(3/5)(4/5) = <strong>24/25</strong>.' },
                    { question: 'If cos θ = 1/2, then cos 2θ =', choices: ['1', '0', '−1/2', '1/2'], correctIndex: 2, explanation: 'cos 2θ = 2(1/4) − 1 = 1/2 − 1 = <strong>−1/2</strong>.' },
                ]}
            ]},

            // ---- 19. Product-to-Sum & Sum-to-Product Identities ----
            { id: 'product-to-sum', title: 'Product-to-Sum & Sum-to-Product Identities', subtitle: 'Converting between products and sums of trig functions', xpReward: 55, sections: [
                { type: 'text', content: `<h3>Product-to-Sum Formulas</h3><p>These formulas are derived directly from the sum and difference identities. By adding or subtracting the formulas for sin(A+B) and sin(A−B), you can convert products of trig functions into sums:</p><p>• <strong>sin A cos B = ½[sin(A+B) + sin(A−B)]</strong><br>• <strong>cos A cos B = ½[cos(A−B) + cos(A+B)]</strong><br>• <strong>sin A sin B = ½[cos(A−B) − cos(A+B)]</strong></p><p>These are especially useful when <strong>integrating products of trig functions</strong> — sums are much easier to integrate than products.</p><h3>Sum-to-Product Formulas</h3><p>Going the other direction, these convert sums into products:</p><p>• <strong>sin α + sin β = 2 sin((α+β)/2) cos((α−β)/2)</strong><br>• <strong>sin α − sin β = 2 cos((α+β)/2) sin((α−β)/2)</strong><br>• <strong>cos α + cos β = 2 cos((α+β)/2) cos((α−β)/2)</strong><br>• <strong>cos α − cos β = −2 sin((α+β)/2) sin((α−β)/2)</strong></p><p>Sum-to-product formulas are useful for <strong>solving equations</strong> where a sum equals zero — you can factor a product and set each factor to zero.</p><h3>When to Use Each</h3><p>• Use <strong>product-to-sum</strong> when you need to simplify a product (common in integration and signal processing).<br>• Use <strong>sum-to-product</strong> when you need to factor or solve an equation involving a sum of trig functions.</p>` },
                { type: 'example', title: 'Product-to-Sum: Express sin 3x cos x as a Sum', content: `<p>Using sin A cos B = ½[sin(A+B) + sin(A−B)] with A = 3x, B = x:</p><p>sin 3x cos x = ½[sin(3x+x) + sin(3x−x)] = ½[sin 4x + sin 2x]</p><p>This result is much easier to integrate than the original product.</p>` },
                { type: 'example', title: 'Sum-to-Product: Simplify sin 5x + sin x', content: `<p>Using sin α + sin β = 2 sin((α+β)/2) cos((α−β)/2) with α = 5x, β = x:</p><p>sin 5x + sin x = 2 sin((5x+x)/2) cos((5x−x)/2) = 2 sin(3x) cos(2x)</p><p>The sum has been converted to a product, which can be solved by setting each factor to zero.</p>` },
                { type: 'generated_practice', generators: ['product-to-sum-apply', 'sum-to-product-apply'] },
                { type: 'practice', problems: [
                    { question: 'sin A cos B = ?', choices: ['½[sin(A+B) − sin(A−B)]', '½[sin(A+B) + sin(A−B)]', '½[cos(A−B) + cos(A+B)]', '½[cos(A−B) − cos(A+B)]'], correctIndex: 1, explanation: '<strong>sin A cos B = ½[sin(A+B) + sin(A−B)]</strong>.' },
                    { question: 'Express sin 2x cos x using product-to-sum:', choices: ['½[sin 3x + sin x]', '½[sin 3x − sin x]', '½[cos x + cos 3x]', '½[sin 2x + sin x]'], correctIndex: 0, explanation: 'sin A cos B = ½[sin(A+B) + sin(A−B)] with A=2x, B=x: <strong>½[sin 3x + sin x]</strong>.' },
                    { question: 'sin α + sin β = ?', choices: ['2 cos((α+β)/2) cos((α−β)/2)', '2 sin((α+β)/2) cos((α−β)/2)', '2 sin((α+β)/2) sin((α−β)/2)', '2 cos((α+β)/2) sin((α−β)/2)'], correctIndex: 1, explanation: '<strong>sin α + sin β = 2 sin((α+β)/2) cos((α−β)/2)</strong>.' },
                    { question: 'Simplify sin 7x + sin 3x using sum-to-product:', choices: ['2 sin(5x) cos(2x)', '2 cos(5x) cos(2x)', '2 sin(5x) sin(2x)', '2 cos(5x) sin(2x)'], correctIndex: 0, explanation: 'α=7x, β=3x: 2 sin((7x+3x)/2) cos((7x−3x)/2) = <strong>2 sin(5x) cos(2x)</strong>.' },
                ]}
            ]},

            // ---- 20. Half-Angle Identities ----
            { id: 'half-angle', title: 'Half-Angle Identities', subtitle: 'Finding trig values for half angles', xpReward: 50, sections: [
                { type: 'text', content: `<h3>Half-Angle Formulas</h3><p>The half-angle formulas are derived by solving the double-angle formulas for the "half" version. Starting from cos 2θ = 1 − 2sin²θ, replace 2θ with θ (so θ becomes θ/2):</p><p>cos θ = 1 − 2sin²(θ/2) → 2sin²(θ/2) = 1 − cos θ → sin²(θ/2) = (1 − cos θ)/2</p><p style="text-align:center;"><strong>sin(θ/2) = ±√[(1 − cos θ)/2]</strong></p><p style="text-align:center;"><strong>cos(θ/2) = ±√[(1 + cos θ)/2]</strong></p><p>These formulas let you find exact values for angles like 22.5° (= 45°/2) or 15° (= 30°/2) that don't appear on the standard unit circle.</p><h3>Choosing the ± Sign</h3><p>The ± depends on which quadrant the <em>half angle</em> (θ/2) falls in — not the original angle θ. Use ASTC:</p><p>• If θ/2 is in <strong>Q1</strong>: sin and cos are both <strong>positive</strong>.<br>• If θ/2 is in <strong>Q2</strong>: sin is <strong>positive</strong>, cos is <strong>negative</strong>.<br>• If θ/2 is in <strong>Q3</strong>: sin and cos are both <strong>negative</strong>.<br>• If θ/2 is in <strong>Q4</strong>: sin is <strong>negative</strong>, cos is <strong>positive</strong>.</p><p>Example: to find sin(15°), use θ = 30°. Since 15° is in Q1, both sin and cos are positive, so take the + root.</p>` },
                { type: 'generated_practice', generators: ['half-angle-eval'] },
                { type: 'practice', problems: [
                    { question: 'sin(θ/2) = ±√[?]', choices: ['(1+cosθ)/2', '(1−cosθ)/2', '(sinθ)/2', '(cosθ−1)/2'], correctIndex: 1, explanation: 'sin(θ/2) = ±√[<strong>(1−cosθ)/2</strong>].' },
                    { question: 'To find sin 15° using half-angle, start with:', choices: ['θ = 15°', 'θ = 30°', 'θ = 45°', 'θ = 60°'], correctIndex: 1, explanation: '15° = 30°/2, so use θ = <strong>30°</strong>.' },
                    { question: 'cos(22.5°) uses which angle as θ?', choices: ['11.25°', '22.5°', '45°', '90°'], correctIndex: 2, explanation: '22.5° = 45°/2, so θ = <strong>45°</strong>.' },
                    { question: 'The ± in half-angle formulas is determined by:', choices: ['The original angle', 'The quadrant of the half angle', 'Always positive', 'Always negative'], correctIndex: 1, explanation: 'Choose + or − based on the <strong>quadrant of the half angle</strong> (θ/2), using ASTC.' },
                ]}
            ]},

            // ---- 21. Trig Identities & Simplification ----
            { id: 'trig-simplification', title: 'Trig Simplification', subtitle: 'Proving and simplifying identities', xpReward: 55, sections: [
                { type: 'text', content: `<h3>Simplifying Trig Expressions</h3><p>Simplifying a trig expression means rewriting it in a cleaner, more compact form using the identities you've learned. There's no single algorithm — it takes practice and pattern recognition — but here are four reliable strategies:</p><p><strong>1. Convert everything to sin and cos.</strong> Replace csc, sec, cot, and tan with their sin/cos equivalents. This puts everything on the same "language," making it easier to spot cancellations.<br>Example: tan θ × cos θ = (sin θ / cos θ) × cos θ = sin θ</p><p><strong>2. Use the Pythagorean identity.</strong> If you see sin²θ + cos²θ, replace it with 1. If you see 1 − sin²θ, replace it with cos²θ. And so on for the other Pythagorean identities.<br>Example: (1 − cos²θ)/sin θ → sin²θ/sin θ = sin θ</p><p><strong>3. Factor.</strong> Just like in algebra, factoring can reveal common terms that cancel.<br>Example: sin²θ + sin θ cos θ = sin θ(sin θ + cos θ)</p><p><strong>4. Multiply by a conjugate.</strong> When you see (1 + cos θ) or (1 − sin θ) in a denominator, multiplying top and bottom by its conjugate can clear it using the Pythagorean identity.<br>Example: 1/(1 − cos θ) × (1 + cos θ)/(1 + cos θ) → (1 + cos θ)/sin²θ</p><p>When <strong>proving an identity</strong>, work on one side only — transform it step by step until it matches the other side. Don't manipulate both sides at once!</p>` },
                { type: 'generated_practice', generators: ['simplify-trig-expr'] },
                { type: 'practice', problems: [
                    { question: 'Simplify: sin²θ + cos²θ + tan²θ', choices: ['1 + tan²θ', 'sec²θ', '2', 'Both A and B'], correctIndex: 3, explanation: 'sin²θ + cos²θ = 1, so 1 + tan²θ = sec²θ. <strong>Both A and B</strong>.' },
                    { question: 'Simplify: (1 − cos²θ)/sinθ', choices: ['sin θ', 'cos θ', 'tan θ', '1'], correctIndex: 0, explanation: '1 − cos²θ = sin²θ. sin²θ/sinθ = <strong>sin θ</strong>.' },
                    { question: 'sec θ cos θ =', choices: ['0', '1', 'sin θ', 'tan θ'], correctIndex: 1, explanation: 'sec θ = 1/cos θ. (1/cos θ)(cos θ) = <strong>1</strong>.' },
                    { question: 'tan θ / sec θ =', choices: ['sin θ', 'cos θ', 'csc θ', 'cot θ'], correctIndex: 0, explanation: '(sinθ/cosθ)/(1/cosθ) = sinθ/cosθ × cosθ = <strong>sin θ</strong>.' },
                ]}
            ]},

            // ---- 22. Polar Coordinates ----
            { id: 'polar-coords', title: 'Polar Coordinates', subtitle: 'Converting between rectangular and polar', xpReward: 50, sections: [
                { type: 'text', content: `<h3>A Different Way to Describe Location</h3><p>You're used to describing points with (x, y) — "go 3 right, 4 up." But sometimes it's more natural to describe a location by <em>how far away</em> it is and <em>which direction</em> — like "5 km away, due north-east." That's the idea behind <strong>polar coordinates</strong>.</p><p>A polar coordinate is written as <strong>(r, θ)</strong>, where:</p><p>• <strong>r</strong> = the distance from the origin (always ≥ 0).<br>• <strong>θ</strong> = the angle measured counter-clockwise from the positive x-axis.</p><p>Polar coordinates are especially useful for circles, spirals, and anything with rotational symmetry — they make those shapes much simpler to describe.</p><h3>Converting Between the Two Systems</h3><p><strong>Polar → Rectangular:</strong><br>x = r cos θ &nbsp; and &nbsp; y = r sin θ</p><p><strong>Rectangular → Polar:</strong><br>r = √(x² + y²) &nbsp; and &nbsp; θ = tan⁻¹(y/x)</p><p>The conversion formulas come directly from the trig definitions — r is the hypotenuse, x is the adjacent side, y is the opposite side.</p>` },
                { type: 'generated_practice', generators: ['rect-to-polar', 'polar-to-rect'] },
                { type: 'practice', problems: [
                    { question: 'Convert (3, 4) to polar: r =', choices: ['5', '7', '12', '25'], correctIndex: 0, explanation: 'r = √(9+16) = √25 = <strong>5</strong>.' },
                    { question: 'Convert (5, 60°) to rectangular: x =', choices: ['5', '2.5', '5√3/2', '5√2/2'], correctIndex: 1, explanation: 'x = 5 cos 60° = 5(1/2) = <strong>2.5</strong>.' },
                    { question: 'In polar coordinates, r represents:', choices: ['The x-coordinate', 'The y-coordinate', 'Distance from origin', 'Angle from x-axis'], correctIndex: 2, explanation: 'r is the <strong>distance from the origin</strong>.' },
                    { question: 'θ in polar coordinates is measured from:', choices: ['The y-axis', 'The positive x-axis', 'The origin', 'North'], correctIndex: 1, explanation: 'θ is measured from the <strong>positive x-axis</strong>.' },
                ]}
            ]},

            // ---- 23. Complex Numbers in Polar Form & DeMoivre's Theorem ----
            { id: 'complex-polar', title: 'Complex Numbers in Polar Form & DeMoivre\'s Theorem', subtitle: 'Polar form, Euler\'s formula, and roots of complex numbers', xpReward: 60, sections: [
                { type: 'text', content: `<h3>Complex Numbers: Rectangular Form Review</h3><p>A complex number in <strong>rectangular form</strong> is z = a + bi, where a is the real part and b is the imaginary part, and i = √(−1). On the complex plane, a is the x-coordinate and b is the y-coordinate.</p><h3>Polar Form</h3><p>Just as a point (a, b) can be expressed in polar coordinates, a complex number can be written in <strong>polar form</strong>:</p><p style="text-align:center;"><strong>z = r(cos θ + i sin θ) = r·cis(θ)</strong></p><p>where:</p><p>• <strong>r = |z| = √(a² + b²)</strong> — the modulus (distance from origin)<br>• <strong>θ = tan⁻¹(b/a)</strong> — the argument (angle from positive real axis)</p><p>This is also written using <strong>Euler's formula</strong>: e<sup>iθ</sup> = cos θ + i sin θ, so z = re<sup>iθ</sup>. Euler's formula is one of the most beautiful results in mathematics, connecting e, i, sin, and cos.</p><h3>Converting Between Forms</h3><p><strong>Rectangular → Polar:</strong> compute r = √(a²+b²) and θ = tan⁻¹(b/a), adjusting θ for the correct quadrant.<br><strong>Polar → Rectangular:</strong> compute a = r cos θ and b = r sin θ.</p><h3>Multiplying in Polar Form</h3><p>Polar form makes multiplication elegant. If z₁ = r₁·cis(θ₁) and z₂ = r₂·cis(θ₂), then:</p><p style="text-align:center;"><strong>z₁ · z₂ = r₁r₂·cis(θ₁ + θ₂)</strong></p><p>Magnitudes <strong>multiply</strong> and angles <strong>add</strong>. This is much simpler than expanding (a+bi)(c+di)!</p><h3>DeMoivre's Theorem</h3><p>Repeated multiplication leads to one of the most powerful results in complex analysis:</p><p style="text-align:center;"><strong>[r·cis(θ)]ⁿ = rⁿ·cis(nθ)</strong></p><p>To raise a complex number to the nth power, raise the modulus to the nth power and multiply the angle by n.</p><h3>Finding nth Roots</h3><p>The nth roots of z = r·cis(θ) are given by:</p><p style="text-align:center;"><strong>r<sup>1/n</sup>·cis((θ + 360°k)/n) &nbsp; for k = 0, 1, 2, ..., n−1</strong></p><p>There are always exactly n distinct nth roots, evenly spaced around a circle of radius r<sup>1/n</sup> on the complex plane.</p>` },
                { type: 'example', title: 'Using DeMoivre\'s Theorem: (1+i)⁸', content: `<p><strong>Step 1 — Convert to polar form.</strong><br>r = √(1²+1²) = √2, θ = tan⁻¹(1/1) = 45°.<br>So 1+i = √2·cis(45°).</p><p><strong>Step 2 — Apply DeMoivre's Theorem.</strong><br>(√2·cis(45°))⁸ = (√2)⁸·cis(8×45°) = 16·cis(360°).</p><p><strong>Step 3 — Convert back.</strong><br>cis(360°) = cos 360° + i sin 360° = 1 + 0i = 1.<br>So (1+i)⁸ = 16·1 = <strong>16</strong>.</p>` },
                { type: 'interactive_steps', title: 'Guided: Compute (1+i)⁴ using DeMoivre\'s Theorem', description: 'Convert to polar form, apply DeMoivre\'s, then convert back.', steps: [
                    { text: 'r = √(1²+1²) = √{blank}', answer: '2', hint: '1²+1² = 2' },
                    { text: 'θ = tan⁻¹(1/1) = {blank}°', answer: '45', hint: 'Equal parts real and imaginary → 45°' },
                    { text: '(√2)⁴ = (2^(1/2))⁴ = 2^(4/2) = 2^{blank}', answer: '2', hint: '4/2 = 2' },
                    { text: '4 × 45° = {blank}°', answer: '180', hint: 'Multiply angle by n = 4' },
                    { text: 'cis(180°) = cos 180° + i sin 180° = {blank}', answer: '-1', hint: 'cos 180° = −1, sin 180° = 0' }
                ], result: '(1+i)⁴ = 4·cis(180°) = 4(−1) = −4' },
                { type: 'generated_practice', generators: ['complex-polar-convert', 'demoivre-power'] },
                { type: 'practice', problems: [
                    { question: 'Express 1+i in polar form:', choices: ['√2·cis(45°)', '2·cis(45°)', '√2·cis(90°)', '1·cis(45°)'], correctIndex: 0, explanation: 'r = √(1+1) = √2, θ = 45°. Polar form: <strong>√2·cis(45°)</strong>.' },
                    { question: 'By DeMoivre\'s Theorem, [2·cis(30°)]³ =', choices: ['8·cis(90°)', '6·cis(90°)', '8·cis(30°)', '6·cis(30°)'], correctIndex: 0, explanation: '2³·cis(3×30°) = <strong>8·cis(90°)</strong>.' },
                    { question: 'How many distinct cube roots does any nonzero complex number have?', choices: ['1', '2', '3', '6'], correctIndex: 2, explanation: 'There are always n distinct nth roots. For cube roots, n = <strong>3</strong>.' },
                    { question: 'When multiplying z₁ = r₁·cis(θ₁) by z₂ = r₂·cis(θ₂), the result is:', choices: ['r₁r₂·cis(θ₁θ₂)', 'r₁r₂·cis(θ₁+θ₂)', '(r₁+r₂)·cis(θ₁+θ₂)', 'r₁r₂·cis(θ₁−θ₂)'], correctIndex: 1, explanation: 'Magnitudes multiply and angles add: <strong>r₁r₂·cis(θ₁+θ₂)</strong>.' },
                ]}
            ]},

            // ---- 24. Vectors ----
            { id: 'vectors', title: 'Vectors', subtitle: 'Magnitude, direction, and operations', xpReward: 50, sections: [
                { type: 'text', content: `<h3>What is a Vector?</h3><p>A <strong>vector</strong> is a quantity that has both a <em>magnitude</em> (size) and a <em>direction</em> — like "60 mph heading north-east." This distinguishes it from a plain number (called a <em>scalar</em>), which has only magnitude.</p><p>We write a 2D vector in component form as <strong>⟨a, b⟩</strong>, meaning "a units right and b units up" (negative values go left/down). You can also picture it as an arrow starting at the origin.</p><h3>Key Vector Operations</h3><p><strong>Magnitude (length):</strong> |v| = √(a² + b²) — just the distance formula from the origin to point (a, b).</p><p><strong>Addition:</strong> ⟨a, b⟩ + ⟨c, d⟩ = ⟨a+c, b+d⟩ — add the components separately. Geometrically, place the second vector's tail at the first vector's head.</p><p><strong>Scalar multiplication:</strong> k⟨a, b⟩ = ⟨ka, kb⟩ — multiply each component by the scalar. This stretches (|k|>1) or shrinks (|k|<1) the vector; negative k reverses its direction.</p><p><strong>The zero vector:</strong> ⟨0, 0⟩ is called the <strong>zero vector</strong> — it has magnitude 0 and no defined direction. It acts like 0 does in regular addition: v + ⟨0,0⟩ = v.</p>` },
                { type: 'generated_practice', generators: ['vector-magnitude', 'vector-add'] },
                { type: 'interactive_steps', title: 'Guided: Find magnitude and direction of v = ⟨3, 4⟩', description: 'Use the magnitude formula and inverse tangent.', steps: [
                    { text: '|v| = √(3² + 4²) = √(9 + {blank})', answer: '16', hint: '4² = 16' },
                    { text: '|v| = √{blank}', answer: '25', hint: '9 + 16' },
                    { text: '|v| = {blank}', answer: '5', hint: '√25' },
                    { text: 'Direction: θ = tan⁻¹(4/3) ≈ {blank}°', answer: '53.1', hint: 'tan⁻¹(1.333...) ≈ ?' }
                ], result: '|v| = 5, θ ≈ 53.1° above the positive x-axis' },
                { type: 'text', content: `<h3>Unit Vectors and Projections</h3><p>A <strong>unit vector</strong> has magnitude 1. To create a unit vector in the direction of v = ⟨a, b⟩, divide each component by the magnitude: û = v/|v| = ⟨a/|v|, b/|v|⟩. This "normalises" the vector — preserving its direction while scaling its length to 1.</p><p>The <strong>standard basis vectors</strong> are î = ⟨1, 0⟩ (pointing right) and ĵ = ⟨0, 1⟩ (pointing up). Any vector can be written in terms of these: ⟨a, b⟩ = aî + bĵ. This decomposition is extremely useful in physics and engineering.</p><p>To find the <strong>component form</strong> of a vector from its magnitude r and angle θ (measured from the positive x-axis):</p><p style="text-align:center;"><strong>v = ⟨r cos θ, r sin θ⟩</strong></p><p>This comes directly from the definition of cos and sin on the unit circle — the vector is just r times the unit vector at angle θ.</p><p>The <strong>projection of u onto v</strong> finds the component of u that lies in the direction of v:</p><p style="text-align:center;"><strong>proj<sub>v</sub>(u) = (u·v / |v|²) v</strong></p><p>The <strong>scalar projection</strong> (also called the component of u along v) is: comp<sub>v</sub>(u) = u·v / |v|.</p>` },
                { type: 'generated_practice', generators: ['unit-vector-calc', 'vector-component-form'] },
                { type: 'practice', problems: [
                    { question: 'Magnitude of ⟨3, 4⟩:', choices: ['5', '7', '12', '1'], correctIndex: 0, explanation: '√(9+16) = √25 = <strong>5</strong>.' },
                    { question: '⟨2, 5⟩ + ⟨3, −1⟩ =', choices: ['⟨5, 4⟩', '⟨5, 6⟩', '⟨−1, 6⟩', '⟨6, 4⟩'], correctIndex: 0, explanation: '⟨2+3, 5+(−1)⟩ = <strong>⟨5, 4⟩</strong>.' },
                    { question: '3⟨1, −2⟩ =', choices: ['⟨3, −6⟩', '⟨3, −2⟩', '⟨4, 1⟩', '⟨1, −6⟩'], correctIndex: 0, explanation: '⟨3(1), 3(−2)⟩ = <strong>⟨3, −6⟩</strong>.' },
                    { question: 'A vector with magnitude 0 is called:', choices: ['Unit vector', 'Zero vector', 'Normal vector', 'Basis vector'], correctIndex: 1, explanation: 'A vector with magnitude 0 is the <strong>zero vector</strong>, written ⟨0, 0⟩.' },
                    { question: 'Unit vector in direction of ⟨3, 4⟩:', choices: ['⟨3, 4⟩', '⟨0.6, 0.8⟩', '⟨1.5, 2⟩', '⟨3/4, 1⟩'], correctIndex: 1, explanation: '|v| = 5. û = ⟨3/5, 4/5⟩ = <strong>⟨0.6, 0.8⟩</strong>.' },
                    { question: 'Component form of vector with magnitude 6 at angle 30°:', choices: ['⟨3√3, 3⟩', '⟨3, 3√3⟩', '⟨6, 6⟩', '⟨3√2, 3√2⟩'], correctIndex: 0, explanation: '⟨6 cos 30°, 6 sin 30°⟩ = ⟨6(√3/2), 6(1/2)⟩ = <strong>⟨3√3, 3⟩</strong>.' },
                ]}
            ]},

            // ---- 25. Dot Product ----
            { id: 'dot-product', title: 'The Dot Product', subtitle: 'Combining vectors and finding angles', xpReward: 50, sections: [
                { type: 'text', content: `<h3>What is the Dot Product?</h3><p>Multiplying two vectors together sounds complicated — but one useful way to do it is the <strong>dot product</strong>, which combines them to produce a single number (a scalar, not another vector).</p><p>For two vectors <strong>u = ⟨u₁, u₂⟩</strong> and <strong>v = ⟨v₁, v₂⟩</strong>:</p><p style="text-align:center;"><strong>u · v = u₁v₁ + u₂v₂</strong></p><p>Multiply corresponding components, then add. That's it!</p><h3>What Does the Dot Product Tell You?</h3><p>The dot product has a beautiful geometric meaning. There's a second formula:</p><p style="text-align:center;"><strong>u · v = |u||v| cos θ</strong></p><p>where θ is the angle <em>between</em> the two vectors. This means:</p><p>• If <strong>u · v = 0</strong>, then cos θ = 0, so θ = 90° — the vectors are <strong>perpendicular</strong> (also called orthogonal).<br>• If <strong>u · v &gt; 0</strong>, the angle between them is less than 90° (they point in roughly the same direction).<br>• If <strong>u · v &lt; 0</strong>, the angle is greater than 90° (they point in roughly opposite directions).</p><p>You can also rearrange the formula to <em>find</em> the angle between two vectors: cos θ = (u · v) / (|u||v|), then use cos⁻¹.</p>` },
                { type: 'generated_practice', generators: ['dot-product-calc'] },
                { type: 'practice', problems: [
                    { question: '⟨2,3⟩ · ⟨4,−1⟩ =', choices: ['5', '11', '8', '−5'], correctIndex: 0, explanation: '2(4) + 3(−1) = 8 − 3 = <strong>5</strong>.' },
                    { question: 'If u · v = 0, the vectors are:', choices: ['Parallel', 'Perpendicular', 'Equal', 'Opposite'], correctIndex: 1, explanation: 'Dot product = 0 means cos θ = 0, so θ = 90° → <strong>perpendicular</strong>.' },
                    { question: 'The dot product produces:', choices: ['A vector', 'A scalar', 'An angle', 'A matrix'], correctIndex: 1, explanation: 'The dot product is a <strong>scalar</strong> (a single number).' },
                    { question: '⟨1,0⟩ · ⟨0,1⟩ =', choices: ['1', '0', '−1', '2'], correctIndex: 1, explanation: '1(0) + 0(1) = <strong>0</strong> (they are perpendicular — one points right, one points up).' },
                ]}
            ]},

            // ---- 26. Sinusoidal Modeling ----
            { id: 'sinusoidal-modeling', title: 'Sinusoidal Modeling', subtitle: 'Real-world periodic functions', xpReward: 50, sections: [
                { type: 'text', content: `<h3>When the Real World Repeats</h3><p>Many real-world phenomena are <strong>periodic</strong> — they repeat on a regular cycle. Ocean tides rise and fall every 12 hours. The temperature in a city goes up each summer and down each winter. A Ferris wheel spins continuously. Sound and light travel as repeating waves. Sinusoidal functions are the mathematical tool for modelling all of these.</p><p>The general model is: <strong>y = A sin(Bx + C) + D</strong> (or with cos instead of sin).</p><p>To build a model from real data, you need four things from the context:</p><p><strong>Amplitude:</strong> half the total range of the quantity.<br><code>A = (max − min) / 2</code></p><p><strong>Vertical shift (midline):</strong> the average of the max and min — the "centre" of the oscillation.<br><code>D = (max + min) / 2</code></p><p><strong>Period:</strong> the time for one complete cycle (given in the problem — e.g., "every 40 seconds").<br><code>Period = 2π / B &nbsp;→&nbsp; B = 2π / Period</code></p><p><strong>Phase shift:</strong> where the cycle starts. Often set to 0 if the context starts at the midline or maximum.</p>` },
                { type: 'generated_practice', generators: ['sinusoidal-from-context'] },
                { type: 'practice', problems: [
                    { question: 'Temperature ranges from 20°F to 80°F. Amplitude =', choices: ['30', '50', '60', '100'], correctIndex: 0, explanation: '(80−20)/2 = <strong>30</strong>.' },
                    { question: 'Same temperature range. Vertical shift (midline) =', choices: ['20', '30', '50', '80'], correctIndex: 2, explanation: '(80+20)/2 = <strong>50</strong>.' },
                    { question: 'A Ferris wheel completes one revolution every 40 seconds. Period =', choices: ['20s', '40s', '80s', '2π'], correctIndex: 1, explanation: 'One full cycle = <strong>40 seconds</strong>.' },
                    { question: 'For period = 40s, B =', choices: ['π/20', '2π/40 = π/20', '40/2π', '20π'], correctIndex: 1, explanation: 'B = 2π/period = 2π/40 = <strong>π/20</strong>.' },
                ]}
            ]},

            // ---- 27. Parametric Equations ----
            { id: 'parametric', title: 'Parametric Equations', subtitle: 'Describing motion with a parameter', xpReward: 50, sections: [
                { type: 'text', content: `<h3>Why Use Parametric Equations?</h3><p>Normally, we describe a curve as y = f(x) — y depends on x. But sometimes x and y both change <em>independently</em> over time, and writing one as a function of the other is awkward or impossible. Think of a ball being thrown: its x-position and y-position both change as time passes, but neither fully controls the other.</p><p>Parametric equations solve this by introducing a third variable — the <strong>parameter</strong>, usually <strong>t</strong> — and expressing x and y separately as functions of t:</p><p style="text-align:center;"><strong>x = f(t) &nbsp; and &nbsp; y = g(t)</strong></p><p>As t varies, the pair (x, y) traces out a curve. The parameter t often represents time, but it can represent angle or distance too.</p><h3>Converting to Rectangular Form</h3><p>Sometimes you want to eliminate t and get a direct relationship between x and y:</p><p>• <strong>Algebraic approach:</strong> Solve one equation for t, then substitute into the other.<br>Example: x = 2t, y = t + 1 → t = x/2 → y = x/2 + 1</p><p>• <strong>Trig identity approach:</strong> If x = r cos t and y = r sin t, use sin²t + cos²t = 1:<br>(x/r)² + (y/r)² = 1 → x² + y² = r². This is a circle with radius r!</p>` },
                { type: 'generated_practice', generators: ['parametric-to-rect'] },
                { type: 'practice', problems: [
                    { question: 'x = 2t, y = t + 1. Eliminate t:', choices: ['y = x/2 + 1', 'y = 2x + 1', 'y = x + 2', 'y = x − 1'], correctIndex: 0, explanation: 't = x/2, so y = x/2 + 1. <strong>y = x/2 + 1</strong>.' },
                    { question: 'x = cos t, y = sin t traces out a:', choices: ['Line', 'Parabola', 'Circle', 'Hyperbola'], correctIndex: 2, explanation: 'cos²t + sin²t = 1 → x² + y² = 1, a <strong>circle</strong>.' },
                    { question: 'x = 3cos t, y = 3sin t traces a circle with radius:', choices: ['1', '3', '9', '6'], correctIndex: 1, explanation: 'x²+y² = 9cos²t + 9sin²t = 9 → radius <strong>3</strong>.' },
                    { question: 'The parameter t often represents:', choices: ['Distance', 'Time', 'Angle', 'All of these'], correctIndex: 3, explanation: 't can represent <strong>all of these</strong> depending on context.' },
                ]}
            ]},

            // ---- 28. Complex Numbers in Trig Form ----
            { id: 'complex-trig', title: 'Complex Numbers in Trig Form', subtitle: 'Modulus, argument, and DeMoivre\'s theorem', xpReward: 55, sections: [
                { type: 'text', content: `<h3>What is a Complex Number?</h3><p>When we tried to solve x² = −1 in algebra, we hit a wall — no real number squares to a negative. Mathematicians extended the number system by defining <strong>i = √(−1)</strong>, the "imaginary unit." A <strong>complex number</strong> combines a real part and an imaginary part:</p><p style="text-align:center;"><strong>z = a + bi</strong></p><p>where a is the real part and b is the imaginary part. Complex numbers can be plotted on the <strong>complex plane</strong>: real on the x-axis, imaginary on the y-axis.</p><h3>Trigonometric Form</h3><p>Just like a point (x, y) can be written in polar form as (r, θ), the complex number a + bi can be written as:</p><p style="text-align:center;"><strong>z = r(cos θ + i sin θ)</strong></p><p>where:</p><p>• <strong>r = √(a² + b²)</strong> is the <em>modulus</em> (also called the absolute value) — the distance from the origin on the complex plane.<br>• <strong>θ = tan⁻¹(b/a)</strong> is the <em>argument</em> — the angle the number makes with the positive real axis.</p><h3>DeMoivre's Theorem</h3><p>Trig form makes <em>powers</em> of complex numbers beautifully simple. DeMoivre's Theorem says:</p><p style="text-align:center;"><strong>[r(cos θ + i sin θ)]ⁿ = rⁿ(cos nθ + i sin nθ)</strong></p><p>Instead of multiplying out a complex number many times, just raise r to the nth power and multiply the angle by n.</p>` },
                { type: 'generated_practice', generators: ['complex-to-trig', 'demoivre-power'] },
                { type: 'practice', problems: [
                    { question: 'Modulus of 3 + 4i:', choices: ['5', '7', '12', '1'], correctIndex: 0, explanation: '|3+4i| = √(9+16) = <strong>5</strong>.' },
                    { question: 'By DeMoivre\'s, [2(cos30°+isin30°)]³ =', choices: ['8(cos90°+isin90°)', '6(cos90°+isin90°)', '8(cos30°+isin30°)', '2(cos90°+isin90°)'], correctIndex: 0, explanation: '2³(cos(3×30°)+isin(3×30°)) = <strong>8(cos90°+isin90°)</strong>.' },
                    { question: 'The argument of 1 + i is:', choices: ['30°', '45°', '60°', '90°'], correctIndex: 1, explanation: 'tan⁻¹(1/1) = <strong>45°</strong>.' },
                    { question: 'The modulus is also called the:', choices: ['Argument', 'Absolute value', 'Conjugate', 'Imaginary part'], correctIndex: 1, explanation: 'The modulus is the <strong>absolute value</strong> of the complex number.' },
                ]}
            ]},

            // ---- 29. Trigonometry Review ----
            { id: 'trig-review', title: 'Trigonometry Review', subtitle: 'Comprehensive problem solving', xpReward: 100, sections: [
                { type: 'text', content: `<h3>You've Made It — Let's Bring It All Together!</h3><p>You've covered the full spectrum of trigonometry — from the first right-triangle ratios all the way through complex numbers and parametric equations. This is genuinely one of the most powerful mathematical toolkits you can have: trig appears in physics, engineering, music, animation, navigation, and countless other fields.</p><p>Use this review to test yourself across the big themes:</p><p>• <strong>Right triangle trig:</strong> SOH-CAH-TOA, inverse functions, solving for sides and angles.<br>• <strong>The unit circle:</strong> special angle values, radians, reference angles, ASTC.<br>• <strong>Graphs:</strong> amplitude, period, phase shift, vertical shift, asymptotes.<br>• <strong>Identities:</strong> Pythagorean, reciprocal, sum/difference, double-angle, half-angle.<br>• <strong>Non-right triangles:</strong> Law of Sines (AAS/ASA/SSA), Law of Cosines (SAS/SSS), area formula.<br>• <strong>Advanced topics:</strong> polar coordinates, vectors, dot product, sinusoidal modelling, parametric equations, complex trig form.</p><p>Don't worry if some topics feel shakier — revisit those lessons, then come back. Each time you review, things click a little more firmly into place.</p>` },
                { type: 'generated_practice', generators: ['unit-circle-coords'] },
                { type: 'generated_practice', generators: ['law-of-cosines-calc'] },
                { type: 'generated_practice', generators: ['trig-double-angle'] },
                { type: 'generated_practice', generators: ['vector-magnitude'] },
                { type: 'practice', problems: [
                    { question: 'sin²θ + cos²θ =', choices: ['0', '1', '2', 'tan θ'], correctIndex: 1, explanation: 'Fundamental identity: <strong>1</strong>.' },
                    { question: 'Convert 270° to radians:', choices: ['π/2', 'π', '3π/2', '2π'], correctIndex: 2, explanation: '270 × π/180 = <strong>3π/2</strong>.' },
                    { question: 'Law of Sines relates:', choices: ['Sides only', 'Angles only', 'Sides to sines of opposite angles', 'Area to perimeter'], correctIndex: 2, explanation: 'a/sinA = b/sinB = c/sinC: <strong>sides to sines of opposite angles</strong>.' },
                    { question: 'Amplitude of y = −4cos(3x) + 1:', choices: ['−4', '3', '4', '1'], correctIndex: 2, explanation: 'Amplitude = |−4| = <strong>4</strong>.' },
                    { question: 'Dot product of ⟨1,2⟩ and ⟨−2,1⟩:', choices: ['0', '4', '−4', '5'], correctIndex: 0, explanation: '1(−2)+2(1) = −2+2 = <strong>0</strong> (perpendicular!).' },
                ]}
            ]},
        ]
};